name: DevSecOps - Security Scans

on:
  workflow_dispatch:
  push:
    branches: [ main ]
     workflow_run:
    workflows: ["Health Check ehrx backend"]
    types:
      - completed
  pull_request:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security:
    name: DevSecOps Security Pipeline
    runs-on: ubuntu-latest

    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    steps:
    
    # 1. Checkout (full history for secret scanning)
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    
    # 2. Secrets Scan (TruffleHog) – FAIL on verified secrets
    
    - name: Secret Scan (TruffleHog)
      run: |
        docker run --rm -v "$(pwd):/pwd" trufflesecurity/trufflehog:latest \
        filesystem /pwd \
        --only-verified \
        --fail \
        --json > trufflehog-report.json

    
    # 3. SAST (Semgrep CI – Correct Usage)
    
    - name: SAST Scan (Semgrep)
      uses: docker://semgrep/semgrep
      with:
        args: >
          semgrep ci
          --sarif
          --output semgrep.sarif

    
    # 4. GitHub Native SAST (CodeQL – Auto Detect Languages) 
    
    # - name: Initialize CodeQL
    #   uses: github/codeql-action/init@v3

    # - name: CodeQL Analysis
    #   uses: github/codeql-action/analyze@v3

    
    # 5. Dependency Vulnerability Scan (Trivy)
    #    FAIL on HIGH & CRITICAL
    
    - name: Dependency Scan (Trivy)
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: fs
        severity: HIGH,CRITICAL
        exit-code: 1
        format: json
        output: trivy-dependency-report.json

    
    # 6. IaC Scan (Terraform / Kubernetes / Helm)
    
    - name: IaC Scan (Trivy)
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: config
        severity: HIGH,CRITICAL
        exit-code: 1
        format: json
        output: trivy-iac-report.json

    
    # 7. Supply Chain Security – SBOM Generation
    
    - name: Generate SBOM (CycloneDX)
      uses: anchore/sbom-action@v0
      with:
        format: cyclonedx-json
        output-file: sbom.json

    
    # 8. Upload Security Artifacts (Audit Evidence)
    
    - name: Upload Security Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-reports
        path: |
          trufflehog-report.json
          semgrep.sarif
          trivy-dependency-report.json
          trivy-iac-report.json
          sbom.json
