name: DevSecOps - Security Scans

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  security:
    name: Security Scans
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Essential for finding secrets in history

      # 1. Secret Scan (TruffleHog)
      - name: Secret Scan (TruffleHog)
        run: |
          docker run --rm -v "$(pwd):/pwd" trufflesecurity/trufflehog:latest \
          filesystem /pwd --json > trufflehog-report.json || true

      # 2. SAST (Semgrep)
      - name: SAST Scan (Semgrep)
        uses: docker://semgrep/semgrep
        with:
          args: >
            semgrep ci
            --sarif
            --output semgrep.sarif
        continue-on-error: true

      # 3. Dependency Scan (Trivy)
      - name: Dependency Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'json'
          output: 'trivy-dependency-report.json'

      # 4. Upload ALL Security Scan Reports
      - name: Upload Security Scan Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-reports
          path: |
            trufflehog-report.json
            semgrep.sarif
            trivy-dependency-report.json
